### ISSUE TITLE
there is no sign up

### ISSUE THREAD

**Issue by p3im4n** [Ansh-Rathod/Flutter-Photoarc-app#1]
hi Mr @Ansh-Rathod 
thanks for your priceless repo!!!
I tested your apk and I saw there was no sign-up page. there was only login and after logining a gray screen!!!
Then I compile the flutter project myself but the same results!!!

could you get me some help??!!!

**Comment by Ansh-Rathod** [comment]
hi,
thanks for your interest in the app.
no, you are going the wrong way. I created an authentication screen in the app where you can sign-up and also sign in on one screen. the logic was if your email already exists in firebase then it will log you in else a new user will be created in firebase.

**Comment by Ansh-Rathod** [comment]
have you tried the released app?

**Comment by p3im4n** [comment]
> I created an authentication screen in the app where you can sign-up and also sign in on one screen. the logic was if your email already exists in firebase then it will log you in else a new user will be created in firebase.

hi dear Mr @Ansh-Rathod
ok...I understand...
the login info is in firebase and user activity like post count and likes and etc.... is in pstgresql...is that right?


> have you tried the released app?

yes, I did it at first but I encountered with the gray screen?
does your backend work properly???

**Comment by Ansh-Rathod** [comment]
yes, exactly

**Comment by Ansh-Rathod** [comment]
yeah my backend work properly

**Comment by p3im4n** [comment]
I live in Iran...I know firebase is filtered here ....so I use VPN....
do you think my problem is that?

**Comment by Ansh-Rathod** [comment]
no,clear app data or uninstall first and  try to create another account. and complete whole sign up process.

**Comment by p3im4n** [comment]
I did it
I use another email to authenticate
But  I have no success
My device is Xiaomi redme 10 android 11

**Comment by Ansh-Rathod** [comment]
i have xiaomi note 10t it works fine on it. backend also works fine in my app and  im using it now.

**Comment by p3im4n** [comment]
the problem was filtering
as I guessed 
I change my VPN then it works....
I have to change the login method to work in my country
maybe I  have to add login with google
thx a lot Mr @Ansh-Rathod 
I close this thread

**Comment by Ansh-Rathod** [comment]
you're welcome
