### ISSUE TITLE
backend ssl

### ISSUE THREAD

**Issue by p3im4n** [Ansh-Rathod/Flutter-Photoarc-app#2]
hi dear Mr @Ansh-Rathod 
I test backend api with postman and this is the result:

POST:
http://103.215.221.153:3000/api/v1/user/create-user

RESPONSE:
{
    "success": false,
    "error": "The server does not support SSL connections",
    "code": 500,
    "results": {
        "message": "The server does not support SSL connections"
    }
}

do I have to set IP to the domain in DNS then get an SSL for the domain??
and how about  POST?
shouldn't it be changed to https://103.215.221.153:3000/api/v1/user/create-user?

**Comment by Ansh-Rathod** [comment]
edit backend db.js
```
 ​import​ ​pg​ ​from​ ​'pg' 
  
 ​const​ ​Pool​ ​=​ ​pg​.​Pool 
// ​const​ ​pool​ ​=​ ​new​ ​Pool​(​{ 
 ​ //       ​connectionString​: ​process​.​env​.​DATABASE_URL​, 
 ​//        ​ssl​: ​{ 
 ​//                ​rejectUnauthorized​: ​false​, 
 //       ​}​, 
// ​}​) 
  
 ​const pool = new Pool({ 
 ​       database: 'postgres', 
 ​       host: 'localhost', 
        port: 5432, 
        user: 'postgres', 
        password: 'ansh00', 
 ​}) 
  
 ​export​ ​default​ ​pool

```

**Comment by p3im4n** [comment]
my db.js:

import pg from 'pg'

const Pool = pg.Pool
const pool = new Pool({
​database: 'postgres',
​host: 'localhost',
port: 5432,
user: 'postgres',
password: '123456',
})

export default pool


the results: 


PS C:\Photoarc-app-backend-nodejs-master> npm run dev

> social_app@1.0.0 dev
> nodemon index

[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node index index.js`
file:///C:/Photoarc-app-backend-nodejs-master/db.js:5
​database: 'postgres',


SyntaxError: Invalid or unexpected token
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:115:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:289:14)
[nodemon] app crashed - waiting for file changes before starting...
