### ISSUE TITLE
workmanager registerPeriodicTask  ios issue

### ISSUE THREAD

**Issue by p3im4n** [Ansh-Rathod/Flutter-Photoarc-app#5]
hi Mr @Ansh-Rathod 
how is everything bro???
unfortunately, workmanager registerPeriodicTask  is not supported in ios
just for the records!!!

**Comment by Ansh-Rathod** [comment]
hiii, everything's alright. and i'm publishing an app too,
and about your problem i don't perfer show notifications using local_notifications plugin in android or ios  anymore 
u should use onesignal push notifications api with your backend which is pretty handy and works in both platforms. if you need anything then email me. Cheers:)
