### ISSUE TITLE
Url.dart

### ISSUE THREAD

**Issue by r16h** [Ansh-Rathod/Flutter-Photoarc-app#7]
Hi Mr @Ansh-Rathod
url.dart file not found
Please send the file to me

**Comment by xNyxs** [comment]
Found fix ??

**Comment by r16h** [comment]
> Found fix ??

@xNyxs  NO

**Comment by IndraRukmana** [comment]
up

**Comment by IndraRukmana** [comment]
up @Ansh-Rathod

**Comment by Ansh-Rathod** [comment]
The url. dart file isn't missing it is removed from the repository by purpose.
url.dart file contains the const variables of backend api URL

For that api, you need to host the backend on any hosting service I prefer to host it on Heroku first check out the readme file of this repo section how to run app :)

**Comment by IndraRukmana** [comment]
can you send commit the missing file?

**Comment by IndraRukmana** [comment]
@Ansh-Rathod

**Comment by Ansh-Rathod** [comment]
It's not a missing file :\

**Comment by Ansh-Rathod** [comment]
You need to create your own file

**Comment by IndraRukmana** [comment]
How is the syntax example?

**Comment by IndraRukmana** [comment]
How is the syntax example?

**Comment by Ansh-Rathod** [comment]
url.dart file

```const BASE_URL= "<YOUR BACKEND URL";```

**Comment by IndraRukmana** [comment]
thanks sir ;)

**Comment by IndraRukmana** [comment]
where is the firebase config? @Ansh-Rathod

**Comment by Ansh-Rathod** [comment]
Create new project in fire base and add google-services.json file in android/app/

**Comment by IndraRukmana** [comment]
ok thanks sir

**Comment by IndraRukmana** [comment]
what version of flutter do you use sir? @Ansh-Rathod

**Comment by IndraRukmana** [comment]
@Ansh-Rathod

**Comment by r16h** [comment]
> The url. dart file isn't missing it is removed from the repository by purpose. url.dart file contains the const variables of backend api URL
> 
> For that api, you need to host the backend on any hosting service I prefer to host it on Heroku first check out the readme file of this repo section how to run app :)

Please explain more because I don't understand anything
